In [66]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [82]:
#load models
model = load_model('models/model.h5')

with open('pickles/onehotencoder.pkl', 'rb') as f:
    onehotencoder = pickle.load(f)

with open('pickles/labelencoder.pkl', 'rb') as f:
    labelencoder = pickle.load(f)

with open('pickles/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [94]:
input_data = {
    'CreditScore': 516,
    'Geography': 'Germany',
    'Gender': 'Female',
    'Age': 21,
    'Tenure' : 1,
    'Balance' : 600,
    'NumOfProducts': 1,
    'HasCrCard': 0,
    'IsActiveMember': 1,
    'EstimatedSalary': 500000,
}

In [95]:
#pre-processing of data encode categorical data, and Geography col - OneHotEncoding
geo_encoder = onehotencoder.transform([[input_data['Geography']]])
geo_encoder_df = pd.DataFrame(geo_encoder, columns=onehotencoder.get_feature_names_out(['Geography']))
geo_encoder_df

/Users/shtlpmac044/Desktop/Manish/Projects/ann-clasification/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [96]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,516,Germany,Female,21,1,600,1,0,1,500000

In [97]:
input_df['Gender'] = labelencoder.fit_transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,516,Germany,0,21,1,600,1,0,1,500000

In [98]:
#concate the categorical and geography cols into final_df
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_encoder_df], axis=1)

In [100]:
#scalling the dataset
scaled_df = scaler.transform(input_df)
scaled_df

array([[-1.40771457, -1.09499335, -1.7015827 , -1.38944225, -1.20886396,
        -0.91668767, -1.54035103,  0.97481699,  6.94716943, -0.99850112,
         1.72572313, -0.57638802]])

In [101]:
#prediction

prediction = model.predict(scaled_df)

prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

array([[0.06342314]], dtype=float32)

In [102]:
prediction_prob = prediction[0][0]

In [103]:
if prediction_prob > 0.5:
  print("Customer is likely to leave the bank")
else:
  print("Customer is likely to stay with the bank")

Customer is likely to stay with the bank